version: '3'

services:
  hadoop-master:
    build: ./hadoop-master
    container_name: hadoop-master
    hostname: hadoop-master
    tty: true
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    networks:
      - hadoop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50070"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  hadoop-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    tty: true
    ports:
      - "8040:8042"
    networks:
      - hadoop

  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    tty: true
    ports:
      - "8041:8042"
    networks:
      - hadoop

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - hadoop

  pyspark:
    build: ./pyspark/
    container_name: pyspark
    tty: true
    depends_on:
      - hadoop-master
      - hadoop-slave1
      - hadoop-slave2
      - mongodb
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge
